baseURL = "https://janusec.github.io/"
languageCode = "en-us"
title = "Janusec"

[menu]

  [[menu.main]]
    name = "Download"
    url = "/dl/"
    weight = 200

  [[menu.main]]
    name = "Github"
    url = "https://github.com/Janusec/janusec"
    weight = 300

  [[menu.main]]
    name = "Documentation"
    url = "/documentation/quick-start/"
    weight = 400
